### ISSUE TITLE
Please cache copyFromDatalayer calls.

### ISSUE THREAD

**Issue by philpott** [Ayudante/parent-element-variable#1]
Each time you call out to copyFromDatalayer Sandbox JS needs to wrap/sanitize the value that is returned so this will have a small performance penalty. To reduce the extra overhead you should cache calls like dataLayer(getPath() + search.searchBottom) that will be consistent across a loops run. 

Example: https://github.com/Ayudante/parent-element-variable/blob/8bc441dde58216d4b6de521d98294ed6bf194657/template.tpl#L476

**Comment by DaisakuHataoka** [comment]
Thank you philpott!

Thanks to the indication, we were able to reduce the number of API calls.
